<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rosbag2_cpp_protobuf_converter</name>
  <version>0.0.1</version>
  <description>Converter plugin for protobuf serialization format in rosbag2</description>
  <maintainer email="lzs_1993@qq.com">lizhensheng</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>pluginlib</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
