<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>protoros2</name>
  <version>0.0.1</version>
  <description>ROS 2 Protobuf extensions and proto2ros CMake wrapper package</description>

  <maintainer email="lzs_1993@qq.com">lizhensheng</maintainer>
  <license>Apache License 2.0</license>

  <author email="lzs_1993@qq.com">lizhensheng</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rmw</depend>
  <depend>proto2ros</depend>
  <depend>rosidl_typesupport_protobuf_cpp</depend>
  <depend>iceoryx_posh</depend>
  <depend>iceoryx_hoofs</depend>
  <depend>flatbuffers</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
